name: Docker Image CI

on:
  push:
    branches: [ master, develop ]

jobs:
  docker-build-and-push:
    name: Docker Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCLOUD_GCR_SERVICE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker

    # Build the Docker image
    - name: Build
      run: |
        docker build . \
        --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${GITHUB_SHA} \
        --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${GITHUB_REF#refs/heads/}
    # Push the Docker image to Google Container Registry
    # by pushing the registry without tag we push all available tags
    - name: Publish
      run: docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}

    # get cloud run name by branch
    - name: Set env to dev
      if: endsWith(github.ref, '/develop')
      run: |
        echo "::set-env name=CLOUD_RUN_NAME::dev-${{ secrets.GCLOUD_APP_NAME }}"
    - name: Set env to production
      if: endsWith(github.ref, '/master')
      run: |
        echo "::set-env name=CLOUD_RUN_NAME::${{ secrets.GCLOUD_APP_NAME }}"

    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        echo "deploy to cloud run $CLOUD_RUN_NAME" && \
        gcloud run deploy "$CLOUD_RUN_NAME" \
          --quiet \
          --region "europe-west1" \
          --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${GITHUB_SHA} \
          --platform "managed" \
          --allow-unauthenticated
